meta-data:
  repository_name: python-package-guideline
  visibility: public
  org-name: RyoNakagami
  tag:
    - uv
    - Python
    - pytest
  description: |
    xxxxx
  homepage: null
  license: mit
